baseURL = 'https://incident.ninja/'
languageCode = 'en-us'
title = 'Incident Ninja Response Methodologies'
disableKinds = ['taxonomy', 'term', 'RSS']
defaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/"
    weight = 1
